swagger: '2.0'
info:
  description: A Production Operator Dashboard (POD) notification is a server-side push message sent to subscribing POD plugins and is triggered as a result of a backend business process. While there are several notifications triggered from core SAP processes, such as SFC Start, it is also possible to send a custom notification to a custom POD plugin.
  version: v1
  title: Production Operator Dashboard Notification
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
host: hostname
basePath: /
security:
- OAuthSecurity: []
produces:
- application/json
consumes:
- application/json
tags:
- name: Notification
paths:
  /send:
    post:
      tags:
      - Notification
      summary: Send a custom notification for consumption by subscribing custom POD plugins.
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - in: body
        name: request
        description: request
        required: true
        schema:
          $ref: '#/definitions/NotificationMessage'
      responses:
        '200':
          description: The message has been sent.
          schema:
            type: string
        '400':
          description: The http request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call or view this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '404':
          description: The resource you are trying to reach is not found.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occurred in the call chain.
          schema:
            $ref: '#/definitions/error'
      description: Send a custom notification to subscribing custom POD plugins. The notification will be routed to any custom plugin that has subscribed to the given event and subscription values. Note that this API cannot send notifications for SAP internal events, such as SFC Start. See the POD Plugin Developer's Guide for details.
      deprecated: false
definitions:
  NotificationMessage:
    type: object
    required:
    - eventName
    - subscription
    properties:
      eventName:
        type: string
        description: The custom notification event name.
      parameters:
        type: array
        description: The notification message payload.
        items:
          $ref: '#/definitions/NotificationParameter'
      subscription:
        $ref: '#/definitions/NotificationSubscription'
    title: NotificationMessage
    description: Contains the notification event name, subscription values, and payload. Any POD plugin that subscribes to the given event and subscription values will receive the notification payload.
  NotificationParameter:
    type: object
    properties:
      name:
        type: string
        description: Parameter Name
      value:
        type: string
        description: Parameter Value
    title: NotificationParameter
    description: A single notification payload value.
  NotificationSubscription:
    type: object
    required:
    - plant
    properties:
      plant:
        type: string
        description: Plant for which notifications should be received.
      operation:
        type: string
        description: Operation for which notifications should be received.
      resource:
        type: string
        description: Resource for which notifications should be received.
      workCenter:
        type: string
        description: Work center for which notifications should be received.
    title: NotificationSubscription
    description: A subscription is a set of plant specific objects that define the context for the business event.  Events that happen within this context will be routed to subscribing plugins. Note that the notification will be sent only if all subscription values match (logical AND).
  error:
    type: object
    properties:
      causeMessage:
        type: string
        description: Contains a technical reason for the error.
      code:
        type: string
        description: Internal error message
      correlationId:
        type: string
        description: Contains a correlation ID for the error.
      message:
        type: string
        description: Contains additional information if any.
    title: error
    description: Error response
securityDefinitions:
  OAuthSecurity:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/operations-guide/prepare-for-api-integration
schemes:
- https
x-sap-shortText: Notification to alert a custom plugin or user about an event that has occurred.
x-servers:
- url: https://api.{regionHost}/notification/v1
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization.
      enum:
      - eu10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication server where SAP Digital Manufacturing is provisioned for your organization.
      enum:
      - eu10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us10.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
