swagger: '2.0'
info:
  title: Production Change
  description: You can use this service to assign new bill of materials and routings to a given shop floor control. You can edit and update SFC-based and order-based orders.
  version: v1
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/apis/production-change
host: hostname
basePath: /
x-sap-shortText: Perform production changes to a shop floor control
x-servers:
- url: https://api.{regionHost}/production/v1
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication token server where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.hana.ondemand.com
      - us10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
schemes:
- https
securityDefinitions:
  OauthClientCredentials:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
security:
- OauthClientCredentials: []
produces:
- application/json
consumes:
- application/json
tags:
- name: Production Change
paths:
  /changeProduction:
    post:
      tags:
      - Production Change
      summary: Assigns a new routing or a new Bill of Materials (BOM) to given Shop Floor Controls (SFCs)
      description: Assigns a new routing or a new Bill of Materials (BOM), or both to given Shop Floor Controls (SFCs). If the relevant order is SFC-based, changes are made at SFC level which means only the specified Shop Floor Controls will be changed. If the relevant order is order-based, then changes are made not only at SFC level, but at order level as well.
      consumes:
      - application/json
      parameters:
      - in: body
        name: request
        description: Request object to change production.
        required: true
        schema:
          $ref: '#/definitions/ChangeProductionRequest'
      responses:
        '200':
          description: Shop floor changes have been made to the production.
          schema:
            $ref: '#/definitions/ChangeProductionResponse'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  ChangeProductionRequest:
    type: object
    description: Request object to change production.
    required:
    - plant
    - sfcs
    properties:
      plant:
        type: string
        description: The plant of the Shop Floor Control.
      sfcs:
        type: array
        description: The list of Shop Floor Controls you want to make changes to.
        items:
          type: string
      routing:
        description: The new routing to be assigned to the Shop Floor Control. If you've filled both 'routing' and 'bom', then the relevant operation activities of the BOM components must exist or partially exist in the newly assigned routing. Otherwise, the assignment will fail.
        $ref: '#/definitions/RoutingId'
      routingStepId:
        description: Specify a particular routing step ID of the new routing. It determines from which routing step the SFC should be started. Based on the original status of the Shop Floor Control (SFC), the SFC will be automatically switched to In Queue or Active status at the routing step. If the property is not set, and the original status of the SFC is New or in Queue, it will be set to In Queue at the first step of the new routing; If the original status of the SFC is Active, it will be set to Active at the first same operation of the new routing.
        type: string
      bom:
        description: The new Bill of Material (BOM) to be assigned to the Shop Floor Control. If you've filled both 'bom' and 'routing', then the relevant operation activities of the BOM components must exist or partially exist in the newly assigned routing. Otherwise, the assignment will fail.
        $ref: '#/definitions/BomId'
      resource:
        type: string
        description: The new resource to be assigned to the Shop Floor Control (SFC). The property only takes effect when specified SFC is in Active status. After production change, the SFC is only visible on the specified resource of the current step.
      operatorID:
        type: string
        description: The new operator who executes the Shop Floor Control (SFC). The property only takes effect when the specified SFC is in Active status. After production change, only this operator could execute the SFC from its current operation. The specified operator must have certification on the material, resource and operation.
  ChangeProductionResponse:
    type: object
    description: Response object of production change.
    properties:
      success:
        type: array
        description: The Shop Floor Controls to change successfully.
        items:
          type: string
      failed:
        type: array
        description: The Shop Floor Controls to change failed.
        items:
          type: string
  RoutingId:
    type: object
    required:
    - routing
    - routingType
    - version
    properties:
      routing:
        type: string
        description: Name of the new routing.
      routingType:
        type: string
        description: The type of the new routing. If the routingType is SHOPORDER_SPECIFIC, while the property 'bom' is not filled, then order-specific Bill of Materials will be assigned to the Shop Floor Control with the assignment of the new routing.
        enum:
        - PRODUCTION
        - SHOPORDER_SPECIFIC
      version:
        type: string
        description: The version of the new routing.
    title: RoutingId
  BomId:
    type: object
    required:
    - bom
    - bomType
    - version
    properties:
      bom:
        type: string
        description: The name of the new Bill of Materials.
      bomType:
        type: string
        description: The type of the new Bill of Materials.
        enum:
        - USERBOM
        - SHOPORDERBOM
        - SFCBOM
      version:
        type: string
        description: The version of the new Bill of Materials.
    title: BomId
  ErrorResponse:
    type: object
    properties:
      message:
        type: string
        description: Contains additional information, if any
      causeMessage:
        type: string
        description: Contains technical reason for the error.
      code:
        type: string
        description: Internal error message
      correlationId:
        type: string
        description: Contains correlationId for the error.
    title: ErrorResponse
    description: Error response.
