swagger: '2.0'
info:
  description: Use this service to create activity confirmation postings in SAP Digital Manufacturing. The activity confirmations are synchronized to integrated ERP systems.
  version: v1
  title: Activity Confirmation
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/operations-guide/prepare-for-api-integration
host: hostname
basePath: /
tags:
- name: Activity Confirmation
  description: Post activity confirmations.
paths:
  /confirm:
    post:
      tags:
      - Activity Confirmation
      summary: Post activity confirmations.
      description: Post activity confirmations for an operation activity, Sfc, order executed at a given workcenter and plant.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: request
        description: Request object to perform activity confirmations.
        required: true
        schema:
          $ref: '#/definitions/ActivityConfirmationPublicAPIRequest'
      responses:
        '200':
          description: Activity confirmation has been completed successfully.
          schema:
            $ref: '#/definitions/ActivityConfirmationPublicAPIResponse'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occurred.
          schema:
            $ref: '#/definitions/error'
      deprecated: false
  /autoconfirm:
    post:
      tags:
      - Activity Confirmation
      summary: Confirms activities automatically.
      description: Confirms activities for the parameters provided as input by automatically calculating the standard values. The standard values are calculated based on the elapsed operation time, on a simple prorated basis.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: request
        description: Request object to confirm activities.
        required: true
        schema:
          $ref: '#/definitions/AutoActivityConfirmationRequest'
      responses:
        '200':
          description: Activities which have been confirmed/calculated.
          schema:
            $ref: '#/definitions/AutoActivityConfirmationResponse'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occurred.
          schema:
            $ref: '#/definitions/error'
  /postings/summary:
    get:
      tags:
      - Activity Confirmation
      summary: Retrieves activity confirmation posting.
      description: Retreives the activity confirmation posting summary for the specified operation activity.
      parameters:
      - in: body
        name: request
        description: Request object to retrieve posting.
        required: true
        schema:
          $ref: '#/definitions/ActivityConfirmationSummaryPublicAPIRequest'
      responses:
        '200':
          description: Activity confirmation posting summary has been retrieved successfully.
          schema:
            $ref: '#/definitions/ActivityConfirmationPublicAPIResponse'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occurred.
          schema:
            $ref: '#/definitions/error'
securityDefinitions:
  OauthClientCredentials:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
security:
- OauthClientCredentials: []
definitions:
  ActivityConfirmationPublicAPIRequest:
    type: object
    title: PostActivityConfirmationRequest
    description: Request object to confirm activities.
    required:
    - plant
    - shopOrder
    - operationActivity
    - stepId
    - workCenter
    - activities
    properties:
      plant:
        description: Plant where activity confirmation has to be performed.
        type: string
      shopOrder:
        description: Shop order for which activity confirmation has to be performed.
        type: string
      sfc:
        description: Sfc of the order for which activity confirmation has to be performed. If the shop order has only one Sfc, this attribute is optional. Else, provide the Sfc.
        type: string
      operationActivity:
        description: Operation activity at which activity confirmation has to be performed.
        type: string
      stepId:
        description: Step Identifier at which activity confirmation has to be performed.
        type: string
      workCenter:
        description: Work center at which activity confirmation has to be performed.
        type: string
      finalConfirmation:
        description: Final confirmation flag for reporting final activity confirmation and completing an operation activity.
        type: boolean
      allowPostingsAfterOperationActivityComplete:
        description: Allows activity confirmation even when the operation activity is completed in SAP Digital Manufacturing. By default, the value is false. If the value is explicitly set to true, then the activities will be posted even though the operation activity is completed.
        type: boolean
      activities:
        type: array
        description: Activity list for which activity confirmation has to be performed.
        items:
          $ref: '#/definitions/ActivityRequestPublicApi'
  ActivityConfirmationSummaryPublicAPIRequest:
    type: object
    title: PostActivityConfirmationSummaryRequest
    description: Request object to retrieve posting.
    required:
    - plant
    - shopOrder
    - sfc
    - operationActivity
    - stepId
    - workCenter
    properties:
      plant:
        description: Plant where activity confirmation has to be performed.
        type: string
      shopOrder:
        description: Shop order for which activity confirmation has to be performed.
        type: string
      sfc:
        description: Sfc of the order for which activity confirmation has to be performed. If the shop order has only one Sfc, this attribute is optional. Else, provide the Sfc.
        type: string
      operationActivity:
        description: Operation activity at which activity confirmation has to be performed.
        type: string
      stepId:
        description: Step Identifier at which activity confirmation has to be performed.
        type: string
      workCenter:
        description: Work center at which activity confirmation has to be performed.
        type: string
  ActivityConfirmationPublicAPIResponse:
    type: object
    title: PostActivityConfirmationResponse
    description: The activity confirmation response.
    properties:
      shopOrder:
        description: Shop order for which activity confirmation has been performed.
        type: string
      operationActivity:
        description: Operation activity at which activity confirmation has been performed.
        type: string
      workCenter:
        description: Work center at which activity confirmation has been performed.
        type: string
      activities:
        type: array
        description: Activity list for which activity confirmation has been performed.
        items:
          $ref: '#/definitions/ActivityResponsePublicApi'
  ActivityRequestPublicApi:
    type: object
    title: ActivityRequest
    description: Request object for activity.
    required:
    - activityId
    - quantity
    - postedBy
    - postingDateTime
    properties:
      activityId:
        description: Activity ID.
        type: string
      quantity:
        description: Quantity for confirmation.
        type: number
      unitOfMeasure:
        description: Unit of measure of the quantity.
        type: string
      isoUnitOfMeasure:
        description: ISO code of the unit of measure of the quantity.
        type: string
      postedBy:
        description: ID of the user who posted the activity confirmation.
        type: string
      postingDateTime:
        type: string
        format: date-time
        example: '2022-04-08T07:00:05.000Z'
        description: The posting date time (in UTC) when the activity confirmation is performed.
  ActivityResponsePublicApi:
    type: object
    title: ActivityResponse
    description: Response object for activity.
    properties:
      activityId:
        description: Activity ID.
        type: string
      quantity:
        description: Quantity confirmed.
        type: number
      unitOfMeasure:
        description: Unit of measure of the confirmed quantity.
        type: string
      isoUnitOfMeasure:
        description: ISO code of the unit of measure of the quantity.
        type: string
      postedBy:
        description: ID of the user who posted the activity confirmation.
        type: string
      postingDateTime:
        type: string
        format: date-time
        example: '2022-04-08T07:00:05.000Z'
        description: The posting date time (in UTC) when the activity confirmation is performed.
  AutoActivityConfirmationRequest:
    type: object
    description: Request object to confirm activities.
    required:
    - plant
    - shopOrder
    - sfc
    - operationActivity
    - operationActivityVersion
    - stepId
    - workCenter
    - resource
    - routingId
    - postedBy
    - postingDateTime
    properties:
      plant:
        type: string
        description: Plant where activity confirmation has to be performed.
      shopOrder:
        type: string
        description: Shop Order for which activity confirmation has to be performed.
      sfc:
        type: string
        description: Sfc at which activity confirmation has to be performed.
      operationActivity:
        description: Operation Activity for which activity confirmation has to be performed.
        type: string
      operationActivityVersion:
        description: Operation Activity Version for which activity confirmation has to be performed.
        type: string
      stepId:
        description: Step Identifier for which activity confirmation has to be performed.
        type: string
      workCenter:
        description: Work center for which activity confirmation has to be performed.
        type: string
      resource:
        description: Resource for which activity confirmation has to be performed.
        type: string
      routingId:
        description: Routing for which activity confirmation has to be performed.
        type: string
      finalConfirmation:
        description: Send final confirmation when posting the activities. The default value is false.
        type: boolean
      postConfirmationToErp:
        description: Post activity confirmations to ERP. The default value is false.
        type: boolean
      postedBy:
        description: ID of the user who posted the activity confirmation.
        type: string
      postingDateTime:
        type: string
        format: date-time
        example: '2022-04-08T07:00:05.000Z'
        description: The posting date time (in UTC) when the activity confirmation is performed.
  AutoActivityConfirmationResponse:
    type: array
    description: Response object of activity confirmation.
    items:
      $ref: '#/definitions/AutoActivityConfirmation'
  AutoActivityConfirmation:
    type: object
    description: Activity confirmation.
    properties:
      activityId:
        description: Activity ID.
        type: string
      quantity:
        description: Quantity for confirmation.
        type: number
      unitOfMeasure:
        description: Unit of measure of the quantity.
        type: string
  error:
    type: object
    required:
    - code
    - message
    - correlationId
    properties:
      code:
        type: string
        description: Internal error message.
      message:
        type: string
        description: Contains additional information, if any.
      correlationId:
        type: string
        description: Contains correlationId for the error.
      causeMessage:
        type: string
        description: Contains technical reason for the error.
x-sap-shortText: Post Activity confirmations
x-servers:
- url: https://api.{regionHost}/activityConfirmation/v1
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication token server where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.hana.ondemand.com
      - us10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
