swagger: '2.0'
info:
  description: A nonconformance group represents a group of nonconformance codes. This API can be used to create, change, delete, and search for nonconformance groups.
  version: v1
  title: Nonconformance Group
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
host: hostname
basePath: /
tags:
- name: Nonconformance Group
  description: Allows you to manage nonconformance groups.
consumes:
- application/json
produces:
- application/json
paths:
  /nonconformancegroups:
    get:
      tags:
      - Nonconformance Group
      summary: Read nonconformance group
      description: Reads nonconformance groups by plant and group
      operationId: readUsingGET
      produces:
      - application/json
      parameters:
      - name: group
        in: query
        description: The nonconformance group value.
        required: false
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      - name: plant
        in: query
        description: The plant where a nonconformance group is defined.
        required: true
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      responses:
        '200':
          description: The nonconformance group was found.
          schema:
            type: array
            items:
              $ref: '#/definitions/NonConformanceGroupV2'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/error'
    post:
      tags:
      - Nonconformance Group
      summary: Create nonconformance group.
      description: Creates a nonconformance group for a given plant
      operationId: createUsingPOST_1
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: nonConformanceGroup
        description: The Nonconformance group to create
        required: true
        schema:
          $ref: '#/definitions/NonConformanceGroupV2'
      responses:
        '201':
          description: The nonconformance group was created.
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '409':
          description: The nonconformance group already exists.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/error'
    delete:
      tags:
      - Nonconformance Group
      summary: Delete nonconformance group.
      description: Deletes a nonconformance group for a given plant
      operationId: deleteUsingDELETE_1
      produces:
      - application/json
      parameters:
      - in: body
        name: request
        description: request
        required: true
        schema:
          $ref: '#/definitions/NonConformanceGroupDeleteRequest'
      responses:
        '204':
          description: The nonconformance group was removed.
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '404':
          description: The nonconformance group was not found.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/error'
    patch:
      tags:
      - Nonconformance Group
      summary: Update nonconformance group.
      description: Updates a nonconformance group for a given plant
      operationId: updateUsingPATCH_1
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: nonConformanceGroup
        description: The nonconformance group to update.
        required: true
        schema:
          $ref: '#/definitions/NonConformanceGroupV2'
      responses:
        '200':
          description: The nonconformance group was updated.
          schema:
            $ref: '#/definitions/NonConformanceGroupV2'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '404':
          description: The nonconformance group was not found.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/error'
securityDefinitions:
  OAuthSecurity:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
definitions:
  NonConformanceGroupDeleteRequest:
    type: object
    required:
    - group
    - plant
    properties:
      group:
        type: string
        description: The nonconformance group value.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      plant:
        type: string
        description: The plant where a nonconformance group is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
    title: NonConformanceGroupDeleteRequest
    description: Nonconformance group delete request.
  NonConformanceGroupV2:
    type: object
    required:
    - group
    - plant
    properties:
      codes:
        type: array
        description: The nonconformance codes assigned to this nonconformance group.
        items:
          $ref: '#/definitions/NonConformanceCodeId'
      createdDateTime:
        type: string
        description: The date and time when the nonconformance group was created.
      description:
        type: string
        description: The nonconformance group description.
      group:
        type: string
        description: The nonconformance group value.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      modifiedDateTime:
        type: string
        description: The date and time when the nonconformance group was updated.
      operationActivities:
        type: array
        description: Operations to validate if nonconfromance group is valid at
        items:
          $ref: '#/definitions/OperationActivityId'
      plant:
        type: string
        description: The plant where a nonconformance group is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      validAtAllOperationActivities:
        type: boolean
        description: Indicates whether to verify if nonconformance group is valid for the specified operations.
    title: NonConformanceGroupV2
    description: Nonconformance group.
  OperationActivityId:
    type: object
    properties:
      operationActivity:
        type: string
        description: Name of the Operation.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      plant:
        type: string
        description: The plant where an operation is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      version:
        type: string
        description: The operation version.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
    title: OperationActivityId
    description: Operation unique data.
  NonConformanceCodeId:
    type: object
    properties:
      code:
        type: string
        description: The nonconformance code value.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      plant:
        type: string
        description: The plant where a nonconformance code is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
    title: NonConformanceCodeId
    description: Nonconformance code unique data.
  error:
    type: object
    properties:
      causeMessage:
        type: string
        description: Contains technical reason for the error.
      code:
        type: string
        description: Internal error message
      correlationId:
        type: string
        description: Contains correlationId for the error.
      message:
        type: string
        description: Contains additional information, if any
    title: error
    description: Error response.
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/operations-guide/prepare-for-api-integration
schemes:
- https
security:
- OAuthSecurity: []
x-sap-shortText: Browse and modify nonconformance groups
x-servers:
- url: https://api.{regionHost}/nonconformancegroup/v1
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication server where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us10.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
