swagger: '2.0'
info:
  description: Retrieves the shift assignments including non-availability of assigned labors to shop floor supervisors of a plant for a date range.
  version: v1
  title: Labor
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
host: hostname
basePath: /
tags:
- name: labor
security:
- OAuthSecurity: []
consumes:
- application/json
produces:
- application/json
paths:
  /laborshiftplans:
    post:
      tags:
      - Labor
      summary: Provides the shift assignments including non-availability of assigned labors to shop floor supervisors of a plant for a given date range.
      description: Retrieves the shift assignments including non-availability of assigned labors to shop floor supervisors of a plant  for a date range. An additional user filter is provided to retrieve shift plans specific to a supervisor.
      operationId: getLaborShiftPlansUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: request
        description: request
        required: true
        schema:
          $ref: '#/definitions/LaborReportRequest'
      responses:
        '200':
          description: Labor report retrieved successfully.
          schema:
            type: array
            items:
              $ref: '#/definitions/LaborReport'
        '400':
          description: Wrong format or structure of the provided request body.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Access denied. You did not have the required permissions to access the resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal server error.
          schema:
            $ref: '#/definitions/ErrorResponse'
      deprecated: false
definitions:
  ErrorResponse:
    type: object
    properties:
      code:
        type: string
        description: Internal error message
      correlationId:
        type: string
        description: Contains a correlation ID for the error.
      message:
        type: string
        description: Contains additional information if any.
    title: ErrorResponse
    description: Error response
  LaborReport:
    type: object
    properties:
      availability:
        type: string
        description: Specifies the availability of the user.
      duration:
        type: string
        description: Specifies the duration of the work center assigned.
      endDate:
        type: string
        description: Specifies the end date of the shift.
      endTime:
        type: string
        description: Specifies the end time of the work center assigned on the shift.
      labor:
        type: string
        description: Specifies the labor.
      maximumResource:
        type: integer
        format: int32
        description: Specifies the maximum number of people that can work on work center.
      mininumResource:
        type: integer
        format: int32
        description: Specifies the minimum number of people that can work on work center.
      qualification:
        type: string
        description: Specifies the qualification/certification of the user.
      shiftModel:
        type: string
        description: Specifies the shift model in which the user is currently in.
      shiftOverTime:
        type: boolean
        description: Specifies the shift overtime.
      startDate:
        type: string
        description: Specifies the start date of the shift.
      startTime:
        type: string
        description: Specifies the start time of the work center assigned on the shift.
      supervisor:
        type: string
        description: Specifies the supervisor.
      unavailabilityType:
        type: string
        description: Specifies the unavailability type.
      workCenter:
        type: string
        description: Specifies the work center Id.
      workCenterDesc:
        type: string
        description: Specifies the work center description.
    title: LaborReport
  LaborReportRequest:
    type: object
    required:
    - endDate
    - plant
    - startDate
    properties:
      endDate:
        type: string
        description: The horizon end date till when shift plans needs to be fetched. Format(YYYYMMDD).
      plant:
        type: string
        description: The plant for which the request is executed.
      startDate:
        type: string
        description: The horizon start date from when the shift plans needs to be fetched. Format(YYYYMMDD).
      user:
        type: string
        description: The email ID of the supervisor who wants to see the shift plans for the labors assigned.
    title: LaborReportRequest
securityDefinitions:
  OAuthSecurity:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/operations-guide/prepare-for-api-integration
schemes:
- https
x-sap-shortText: Retrieves the shift assignments including non-availability of assigned labors.
x-servers:
- url: https://api.{regionHost}/labor/v1
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization.
      enum:
      - eu10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication server where SAP Digital Manufacturing is provisioned for your organization.
      enum:
      - eu10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us10.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
