swagger: '2.0'
info:
  description: A plant is a specific, discrete area where you manufacture a product. This API can be called to retrieve all plants or specific plant by name.
  version: v1
  title: Plant
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
host: hostname
basePath: /
tags:
- name: Plant
  description: Plant Api Controller
consumes:
- application/json
produces:
- application/json
security:
- OauthClientCredentials: []
paths:
  /plants:
    get:
      tags:
      - Plant
      summary: Searches for plants.
      description: Finds all plants or or specific plant by name.
      operationId: getPlantUsingGET
      produces:
      - application/json
      parameters:
      - name: plant
        in: query
        description: The plant name.
        required: false
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      responses:
        '200':
          description: Returns a list of plants.
          schema:
            type: array
            items:
              $ref: '#/definitions/Plant'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/error'
      security:
      - OauthClientCredentials: []
      deprecated: false
securityDefinitions:
  OauthClientCredentials:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
definitions:
  Plant:
    type: object
    properties:
      client:
        type: string
        description: The client for the integration with SAP Digital Manufacturing for insights.
      createdOn:
        type: string
        format: date-time
        example: '2021-04-08T07:00:05.000Z'
        description: The date and time (in UTC) when the plant was created.
      description:
        type: string
        description: The plant description.
      eccLogicalSystem:
        type: string
        description: The ECC Logical System for EWM Integration.
      erpDestination:
        type: string
        description: The ERP destination.
      erpLanguage:
        type: string
        description: The ERP plant language.
      erpTimeZone:
        type: string
        description: The plant time zone for ERP system.
      ewmDestination:
        type: string
        description: The EWM destination.
      ewmProgramId:
        type: string
        description: The EWM program ID.
      fsmScenarioZero:
        type: boolean
        description: Indicates if the FSM scenario zero is enabled.
      industryType:
        type: string
        description: Discrete or process industry terminology is applied to this plant.
        enum:
        - DISCRETE
        - PROCESS
      integrationMode:
        type: string
        description: The integration is enabled with SAP S/4HANA or SAP S/4HANA Cloud.
        enum:
        - S4HANA_CLOUD
        - S4HANA_OP_W_CPI
      isLocal:
        type: boolean
        description: Indicates that the plant is local or remote.
      materialUpversion:
        type: boolean
        description: Indicates that the material version update logic is enabled for this plant.
      meSystem:
        type: string
        description: The ME system for the integration with SAP Digital Manufacturing for insights.
      miiSystem:
        type: string
        description: The MII system for the integration with SAP Digital Manufacturing for insights.
      modifiedOn:
        type: string
        format: date-time
        example: '2021-04-08T07:00:05.000Z'
        description: The date and time (in UTC) when the the plant was updated.
      plant:
        type: string
        description: The plant name.
      timeZone:
        type: string
        description: The time zone for the plant.
    title: Plant
    description: Plant
  error:
    type: object
    properties:
      causeMessage:
        type: string
        description: Contains a technical reason for the error.
      code:
        type: string
        description: Internal error message
      correlationId:
        type: string
        description: Contains a correlation ID for the error.
      message:
        type: string
        description: Contains additional information if any.
    title: error
    description: Error response
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/operations-guide/prepare-for-api-integration
schemes:
- https
x-sap-shortText: Get a list of plants.
x-servers:
- url: https://api.{regionHost}/plant/v1
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication server where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us10.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
