swagger: '2.0'
info:
  title: Speed Loss
  description: You can use this service to report speed loss. Speed loss is the production time lost due to equipment running below its maximum rated speed.
  version: v1
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/operations-guide/prepare-for-api-integration
host: hostname
basePath: /
x-sap-shortText: Create speed loss with reason code
x-servers:
- url: https://api.{regionHost}/oee
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication token server where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.hana.ondemand.com
      - us10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
schemes:
- https
securityDefinitions:
  OauthClientCredentials:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
security:
- OauthClientCredentials: []
produces:
- application/json
consumes:
- application/json
paths:
  /v1/speedLoss:
    post:
      tags:
      - Speed Loss
      summary: Creates speed loss
      description: Create a new speed loss with Reason Code tagged. You can tag the existing un-tagged speed loss with a reason code for a given duration.
      consumes:
      - application/json
      parameters:
      - in: body
        name: request
        description: Request object to create speed loss.
        required: true
        schema:
          $ref: '#/definitions/SpeedLossCreateRequest'
      responses:
        '201':
          description: Speed loss has been created successfully.
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  SpeedLossCreateRequest:
    description: A request to report speed loss
    required:
    - plant
    - order
    - operationActivity
    - resource
    - resourceReasonCodeId
    - date
    - duration
    properties:
      plant:
        description: Plant for reporting speed loss.
        type: string
      order:
        description: Order for reporting speed loss.
        type: string
      operationActivity:
        description: Operation Activity for reporting speed loss.
        example: 1015301-0-0020
        type: string
      resource:
        description: Resource name for reporting speed loss.
        type: string
      resourceReasonCodeId:
        description: Reason code Id(Key Id) for reporting speed loss.
        type: string
      date:
        description: Date on which speed loss is reported in yyyy-MM-dd format.
        example: '2022-02-01'
        type: string
      shift:
        description: Shift Name for reporting speed loss.
        type: string
      duration:
        description: Duration of speed loss in milliseconds.
        type: number
  ErrorResponse:
    type: object
    properties:
      causeMessage:
        type: string
        description: Contains technical reason for the error.
      code:
        type: string
        description: Internal error message
      correlationId:
        type: string
        description: Contains correlationId for the error.
      message:
        type: string
        description: Contains additional information, if any
    title: ErrorResponse
    description: Error response.
