swagger: '2.0'
info:
  description: A Work Center can be a place or a machine or a labor where production operations/activities are performed. This API can be used to create, change, delete, and search for work centers.
  version: v2
  title: Work Center
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
host: hostname
basePath: /
tags:
- name: Work Center
  description: Work Center Api V2 Controller
consumes:
- application/json
produces:
- application/json
security:
- OauthClientCredentials: []
paths:
  /workcenters:
    get:
      tags:
      - Work Center
      summary: Searches for work centers by plant and work center values.
      description: Searches for a work center for a given plant and returns the details for the same.
      operationId: readUsingGET
      produces:
      - application/json
      parameters:
      - name: plant
        in: query
        description: The plant where a work center is defined.
        required: true
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      - name: workCenter
        in: query
        description: The work center value.
        required: false
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      - name: assignedUser
        in: query
        description: The user identifier.
        required: false
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      - name: resourceMembers
        in: query
        description: The resource members.
        required: false
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      responses:
        '200':
          description: The work center was found.
          schema:
            type: array
            items:
              $ref: '#/definitions/WorkCenterV2'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: The plant was not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/ErrorResponse'
    post:
      tags:
      - Work Center
      summary: Creates a work center.
      description: Creates a work center for a given plant.
      operationId: createUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: workCenter
        description: The work center to create
        required: true
        schema:
          $ref: '#/definitions/WorkCenterV2'
      responses:
        '201':
          description: The work center was created
          schema:
            $ref: '#/definitions/WorkCenterV2'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: The plant was not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '409':
          description: The work center already exists.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - Work Center
      summary: Removes the given work center.
      description: Removes a work center for a given plant
      operationId: deleteUsingDELETE
      produces:
      - application/json
      parameters:
      - in: body
        name: request
        description: request
        required: true
        schema:
          $ref: '#/definitions/WorkCenterDeleteRequest'
      responses:
        '204':
          description: The work center was removed.
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: The work center or plant was not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/ErrorResponse'
    patch:
      tags:
      - Work Center
      summary: Updates the given work center.
      description: Updates a work center for a given plant.
      operationId: updateUsingPATCH
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: workCenter
        description: The work center to update
        required: true
        schema:
          $ref: '#/definitions/WorkCenterV2'
      responses:
        '200':
          description: The work center was updated.
          schema:
            $ref: '#/definitions/WorkCenterV2'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: The work center or plant was not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/ErrorResponse'
securityDefinitions:
  OauthClientCredentials:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
definitions:
  CustomValue:
    title: CustomValue
    description: Custom value
    type: object
    properties:
      attribute:
        type: string
      value:
        type: string
  WorkCenterV2:
    title: WorkCenterV2
    description: Work center
    type: object
    required:
    - plant
    - workCenter
    - status
    properties:
      plant:
        type: string
        description: The plant where a work center is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      workCenter:
        type: string
        description: The work center value.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      status:
        type: string
        description: The work center status.
        enum:
        - DISABLED
        - ENABLED
      canBeReleasedTo:
        type: boolean
        description: Indicates if this work center can be released.
      category:
        type: string
        description: Defines the category of the work center.
        enum:
        - BUILDING
        - CELL
        - CELL_GROUP
        - LINE
        - LINE_GROUP
        - NONE
      description:
        type: string
        description: The work center description.
      isErp:
        type: boolean
        description: Indicates if a work center was transferred from SAP ERP.
      maxNumberPeople:
        type: integer
        format: int32
        description: Defines a maximum number of people for this work center.
      minNumberPeople:
        type: integer
        format: int32
        description: Defines a minimum number of people for this work center.
      productionSupplyArea:
        type: string
        description: Defines a production supply area.
      oeeMembers:
        type: array
        description: Work center OEE members
        items:
          $ref: '#/definitions/WorkCenterOeeMember'
      members:
        type: array
        description: Work center members
        items:
          $ref: '#/definitions/WorkCenterMemberV2'
      userAssignments:
        type: array
        description: The users who are assigned to this work center.
        items:
          $ref: '#/definitions/UserAssignmentId'
      customValues:
        type: array
        description: Work center custom values
        items:
          $ref: '#/definitions/CustomValue'
      createdOn:
        type: string
        example: '2021-07-29T03:53:33Z'
        description: 'The date and time when the work center was created. Format (ISO-8601): yyyy-MM-dd''T''HH:mm:ss''Z'''
      modifiedOn:
        type: string
        example: '2021-07-29T03:53:33Z'
        description: 'The date and time when the the work center was updated. Format (ISO-8601): yyyy-MM-dd''T''HH:mm:ss''Z'''
  WorkCenterMemberV2:
    title: WorkCenterMemberV2
    description: Defines the resources and work centers that are part of this work center.
    type: object
    properties:
      resource:
        description: Associated resource.
        $ref: '#/definitions/ResourceId'
      workCenter:
        description: Associated work center.
        $ref: '#/definitions/WorkCenterId'
      defaultMember:
        type: boolean
        description: Indicates if it is a default member.
      monitoringRelevant:
        type: boolean
        description: Indicates if it is relevant for monitoring.
      schedulingRelevant:
        type: boolean
        description: Indicates if it is relevant for scheduling.
  WorkCenterOeeMember:
    title: WorkCenterOeeMember
    description: Defines resource memebers that are part of the OEE hierarchy.
    type: object
    properties:
      bottleneckMultiplier:
        type: number
        description: Represents a bottleneck multiplier.
      isBottleneck:
        type: boolean
        description: Indicates if this resource is a bottleneck.
      resource:
        description: The resource identifier.
        $ref: '#/definitions/ResourceId'
      status:
        type: string
        description: The status of the OEE work center member.
        enum:
        - DISABLED
        - ENABLED
      members:
        type: array
        description: Members of this node.
        items:
          $ref: '#/definitions/WorkCenterOeeMemberNode'
  WorkCenterOeeMemberNode:
    title: WorkCenterOeeMemberNode
    description: Defines resource memebers that are part of the OEE hierarchy.
    type: object
    properties:
      bottleneckMultiplier:
        type: number
        description: Represents a bottleneck multiplier.
      isBottleneck:
        type: boolean
        description: Indicates if this resource is a bottleneck.
      resource:
        description: The resource identifier.
        $ref: '#/definitions/ResourceId'
      status:
        type: string
        description: The status of the OEE work center member.
        enum:
        - DISABLED
        - ENABLED
  UserAssignmentId:
    title: UserAssignmentId
    description: The user unique data.
    type: object
    required:
    - plant
    - userId
    properties:
      plant:
        type: string
        description: The plant where a user is created.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      userId:
        type: string
        description: The user identifier.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
  WorkCenterDeleteRequest:
    title: WorkCenterDeleteRequest
    description: Work center delete request.
    type: object
    required:
    - plant
    - workCenter
    properties:
      plant:
        type: string
        description: The plant where a work center is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      workCenter:
        type: string
        description: The work center value.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
  ResourceId:
    title: ResourceId
    description: Resource identifier.
    type: object
    required:
    - plant
    - resource
    properties:
      plant:
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      resource:
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
  WorkCenterId:
    title: WorkCenterId
    description: Work center identifier.
    type: object
    required:
    - plant
    - workcenter
    properties:
      plant:
        type: string
      workcenter:
        type: string
  ErrorResponse:
    title: error
    description: Error response
    type: object
    properties:
      causeMessage:
        type: string
        description: Contains a technical reason for the error.
      code:
        type: string
        description: Internal error message
      correlationId:
        type: string
        description: Contains a correlation ID for the error.
      message:
        type: string
        description: Contains additional information if any.
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/operations-guide/prepare-for-api-integration
schemes:
- https
x-sap-shortText: Maintain work centers for a given plant.
x-servers:
- url: https://api.{regionHost}/workcenter/v2
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication server where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us10.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
