swagger: '2.0'
info:
  title: Process Manufacturing Execution
  description: Provides functionality for production order or process order execution related to Process Manufacturing. For example, starting an operation activity, completing an operation activity.
  version: v1
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/operations-guide/prepare-for-api-integration
host: hostname
basePath: /
x-sap-shortText: Perform production activities for a production order or process order, such as start an operation activity, complete an operation activity
x-servers:
- url: https://api.{regionHost}/order/v1
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication token server where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.hana.ondemand.com
      - us10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
schemes:
- https
securityDefinitions:
  OauthClientCredentials:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
security:
- OauthClientCredentials: []
produces:
- application/json
consumes:
- application/json
tags:
- name: Operation Activity Processing
paths:
  /operationActivity/start:
    post:
      tags:
      - Operation Activity Processing
      summary: Starts an Operation activity.
      description: Starts an Operation activity at the default or alternate resource of a work center at user-specified time or in real time.
      consumes:
      - application/json
      parameters:
      - in: body
        name: request
        description: Request object to start an Operation activity.
        required: true
        schema:
          $ref: '#/definitions/StartOperationActivityPublicApiRequest'
      responses:
        '200':
          description: Operation activity has been started successfully.
          schema:
            $ref: '#/definitions/StartOperationActivityPublicApiResponse'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/OperationActivityErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/OperationActivityErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/OperationActivityErrorResponse'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/OperationActivityErrorResponse'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/OperationActivityErrorResponse'
  /operationActivity/complete:
    post:
      tags:
      - Operation Activity Processing
      summary: Completes an Operation activity.
      description: Completes an operation activity at the default or alternate resource of a work center at user-specified time or in real time.
      consumes:
      - application/json
      parameters:
      - in: body
        name: request
        description: Request object to complete an Operation activity.
        required: true
        schema:
          $ref: '#/definitions/CompleteOperationActivityPublicApiRequest'
      responses:
        '200':
          description: Operation activity has been completed successfully.
          schema:
            $ref: '#/definitions/CompleteOperationActivityPublicApiResponse'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/OperationActivityErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/OperationActivityErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/OperationActivityErrorResponse'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/OperationActivityErrorResponse'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/OperationActivityErrorResponse'
definitions:
  StartOperationActivityPublicApiRequest:
    type: object
    description: Request object to start an operation activity.
    required:
    - plant
    - order
    - sfc
    - operationActivity
    - workCenter
    properties:
      plant:
        description: Plant where the operation activity has to be started.
        type: string
      order:
        description: Order of the operation activity.
        type: string
      sfc:
        description: SFC of the order.
        type: string
      operationActivity:
        description: Operation activity to be started.
        type: string
      workCenter:
        description: Work center to start the operation activity on.
        type: string
      actualStartDateTime:
        description: Start date and time of the operation activity in UTC. If not provided, start would be real time.
        type: string
        format: date-time
        example: '2022-04-23T09:53:03Z'
  StartOperationActivityPublicApiResponse:
    type: object
    description: Response object of start operation activity.
    properties:
      plant:
        description: Plant where the operation activity has been started.
        type: string
      order:
        description: Order of the operation activity.
        type: string
      sfc:
        description: SFC of the order.
        type: string
      operationActivity:
        description: Operation activity that is started.
        type: string
      workCenter:
        description: Work center where the operation activity is started.
        type: string
      actualStartDateTime:
        description: Requested start time of the operation activity in UTC.
        type: string
        format: date-time
        example: '2022-04-23T09:53:03Z'
  CompleteOperationActivityPublicApiRequest:
    type: object
    description: Request object to complete an operation activity.
    required:
    - plant
    - order
    - sfc
    - operationActivity
    - workCenter
    properties:
      plant:
        description: Plant where the operation activity has to be completed.
        type: string
      order:
        description: Order of the operation activity.
        type: string
      sfc:
        description: SFC of the order.
        type: string
      operationActivity:
        description: Operation activity to be completed.
        type: string
      workCenter:
        description: Work center to complete the operation activity on.
        type: string
      actualCompleteDateTime:
        description: Completion date and time of the operation activity in UTC. If not provided, complete would be real time.
        type: string
        format: date-time
        example: '2022-04-23T09:53:03Z'
      finalConfirmation:
        description: Send final confirmation when completing the operation activity.
        type: boolean
        default: false
  CompleteOperationActivityPublicApiResponse:
    type: object
    description: Response object of complete operation activity.
    properties:
      plant:
        description: Plant where the operation activity has been completed.
        type: string
      order:
        description: Order of the operation activity.
        type: string
      sfc:
        description: SFC of the order.
        type: string
      operationActivity:
        description: Operation activity that is completed.
        type: string
      workCenter:
        description: Work center where the operation activity is completed.
        type: string
      actualCompleteDateTime:
        description: Requested completion date and time of the operation activity.
        type: string
        format: date-time
        example: '2022-04-23T09:53:03Z'
      finalConfirmation:
        description: Requested final confirmation flag value.
        type: boolean
  OperationActivityErrorResponse:
    type: object
    properties:
      causeMessage:
        type: string
        description: Contains technical reason for the error.
      code:
        type: string
        description: Internal error message
      correlationId:
        type: string
        description: Contains correlationId for the error.
      message:
        type: string
        description: Contains additional information, if any
    title: ErrorResponse
    description: Error response.
