swagger: '2.0'
info:
  description: A nonconformance code is a distinct set of characters that represent a failure, defect, or repair code indicating that the shop floor control doesn’t meet the approved quality definition. Use this service  to search, create, update, and delete nonconformance codes.
  version: v1
  title: Nonconformance Code
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
host: hostname
basePath: /
tags:
- name: Nonconformance Code
  description: Allows you to manage nonconformance codes.
consumes:
- application/json
produces:
- application/json
paths:
  /nonconformancecodes:
    get:
      tags:
      - Nonconformance Code
      summary: Read nonconformance code
      description: Reads a nonconformance code for a given plant and returns the details for the same
      operationId: readNonConformanceCodesUsingGET
      produces:
      - application/json
      parameters:
      - name: code
        in: query
        description: The nonconformance code value.
        required: false
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      - name: plant
        in: query
        description: The plant where a nonconformance code is defined.
        required: true
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      responses:
        '200':
          description: The nonconformance code was found.
          schema:
            type: array
            items:
              $ref: '#/definitions/NonConformanceCodeV2'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/error'
    post:
      tags:
      - Nonconformance Code
      summary: Create nonconformance code.
      description: Creates a nonconformance code for a given plant
      operationId: createUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: The Nonconformance code to create
        description: nonConformanceCode
        required: true
        schema:
          $ref: '#/definitions/NonConformanceCodeV2'
      responses:
        '201':
          description: The nonconformance code was created.
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '409':
          description: The nonconformance code already exists.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/error'
    delete:
      tags:
      - Nonconformance Code
      summary: Delete nonconformance code.
      description: Deletes a nonconformance code for a given plant
      operationId: deleteUsingDELETE
      produces:
      - application/json
      parameters:
      - in: body
        name: request
        description: request
        required: true
        schema:
          $ref: '#/definitions/NonConformanceCodeDeleteRequest'
      responses:
        '204':
          description: The nonconformance code was removed.
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '404':
          description: The nonconformance code was not found.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/error'
    patch:
      tags:
      - Nonconformance Code
      summary: Update nonconformance code.
      description: Updates a nonconformance code for a given plant
      operationId: updateUsingPATCH
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: nonConformanceCode
        description: The nonconformance code to update.
        required: true
        schema:
          $ref: '#/definitions/NonConformanceCodeV2'
      responses:
        '200':
          description: The nonconformance code was updated.
          schema:
            $ref: '#/definitions/NonConformanceCodeV2'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/error'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/error'
        '404':
          description: The nonconformance code was not found.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/error'
securityDefinitions:
  OAuthSecurity:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
definitions:
  NonConformanceCodeDeleteRequest:
    type: object
    required:
    - code
    - plant
    properties:
      code:
        type: string
        description: The nonconformance code value to delete.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      plant:
        type: string
        description: The plant where a nonconformance code is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
    title: NonConformanceCodeDeleteRequest
    description: Nonconformance code delete request.
  NonConformanceCodeV2:
    type: object
    required:
    - code
    - plant
    properties:
      category:
        type: string
        description: The nonconformance code category.
        enum:
        - DEFECT
        - FAILURE
        - REPAIR
      code:
        type: string
        description: The nonconformance code value.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      createdDateTime:
        type: string
        description: The date and time when the nonconformance code was created.
      customData:
        type: array
        description: The nonconformance code custom values.
        items:
          $ref: '#/definitions/CustomValue'
      description:
        type: string
        description: The nonconformance code description.
      groups:
        type: array
        description: The nonconformance groups to be assigned.
        items:
          $ref: '#/definitions/NonConformanceGroupId'
      modifiedDateTime:
        type: string
        description: The date and time when the nonconformance code was updated.
      plant:
        type: string
        description: The plant where a nonconformance code is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      status:
        type: string
        description: The nonconformance code status.
        enum:
        - DISABLED
        - ENABLED
    title: NonConformanceCodeV2
    description: Nonconformance code.
  CustomValue:
    type: object
    properties:
      attribute:
        type: string
      value:
        type: string
    title: CustomValue
  NonConformanceGroupId:
    type: object
    properties:
      group:
        type: string
        description: The nonconformance group value.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      plant:
        type: string
        description: The plant where a nonconformance code is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
    title: NonConformanceGroupId
    description: Nonconformance group unique data.
  error:
    type: object
    properties:
      causeMessage:
        type: string
        description: Contains technical reason for the error.
      code:
        type: string
        description: Internal error message
      correlationId:
        type: string
        description: Contains correlationId for the error.
      message:
        type: string
        description: Contains additional information, if any
    title: error
    description: Error response.
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/operations-guide/prepare-for-api-integration
schemes:
- https
security:
- OAuthSecurity: []
x-sap-shortText: Manage nonconformance codes
x-servers:
- url: https://api.{regionHost}/nonconformancecode/v1
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication server where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us10.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
