swagger: '2.0'
info:
  description: You can use this service to create a Production Operator Dashboards (POD) and to export or import POD configurations. You can transfer and share POD configurations across plants, landscapes, or among users.
  version: v1
  title: Production Operator Dashboard
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/operations-guide/prepare-for-api-integration
host: hostname
basePath: /
security:
- OauthClientCredentials: []
x-sap-shortText: Create, import, and export a Production Operator Dashboard
x-servers:
- url: https://api.{regionHost}/pod/v1
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication server where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us10.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
schemes:
- https
securityDefinitions:
  OauthClientCredentials:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
tags:
- name: Production Operator Dashboard
consumes:
- multipart/form-data
- application/json
produces:
- application/json
paths:
  /configurations:
    post:
      tags:
      - Production Operator Dashboard
      summary: API to create a new POD given a POD configuration.
      description: This end point creates a new a POD with the given POD identity and configuration. The configuration must be a string representing a valid json.
      operationId: createPodConfigurationUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: configRequest
        description: configRequest
        required: true
        schema:
          $ref: '#/definitions/PodConfigRequest'
      responses:
        '201':
          description: Have successfully created a ne POD using the given configuration content.
          schema:
            $ref: '#/definitions/PodConfigResponse'
        '400':
          description: The http request is bad or invalid and can not be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
        '409':
          description: The POD with the given ID already exists.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/error'
  /export:
    get:
      tags:
      - Production Operator Dashboard
      summary: API to export a POD configuration.
      description: The end point retrieves a POD configuration and  saves it to a local file system. If the call is made directly by supported browsers, the browser will prompt for a local file selection, otherwise a the configuration is returned directly as the output.
      operationId: exportPodUsingGET
      produces:
      - application/json
      parameters:
      - name: plant
        in: query
        description: The Plant for the exporting POD.
        required: true
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      - name: podId
        in: query
        description: The POD identity.
        required: true
        type: string
        maxLength: 40
        minLength: 1
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-. ]+(?<! )$
      responses:
        '200':
          description: Have successfully retrieved the configuration and saved to file system.
          schema:
            type: file
        '400':
          description: The http request is bad or invalid and can not be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
        '404':
          description: The POD with the given ID does not exist.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/error'
  /import:
    post:
      tags:
      - Production Operator Dashboard
      summary: API to import a POD configuration from a local file system and creating a new POD.
      description: The body of this call must conform to the requirements of HTTP form-data format.
      operationId: importPodUsingPOST
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - in: formData
        name: file
        description: The file to upload.
        required: true
        type: file
      - name: plant
        in: formData
        description: plant
        required: true
        type: string
        maxLength: 6
        minLength: 1
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      - name: podDescription
        in: formData
        description: podDescription
        required: false
        type: string
        maxLength: 40
      - name: podId
        in: formData
        description: podId
        required: true
        type: string
        maxLength: 40
        minLength: 1
      responses:
        '201':
          description: Have successfully created a new POD using the given configuration content.
          schema:
            $ref: '#/definitions/PodConfigResponse'
        '400':
          description: The http request is bad or invalid and can not be processed by the server.
          schema:
            $ref: '#/definitions/error'
        '401':
          description: You are not authorized to call this resource.
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
        '409':
          description: The POD with the given ID already exists.
          schema:
            $ref: '#/definitions/error'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/error'
        '503':
          description: Content scanner has detected malware.
          schema:
            $ref: '#/definitions/error'
definitions:
  PodConfigRequest:
    type: object
    required:
    - configData
    - plant
    - podId
    properties:
      configData:
        type: string
        description: The POD configuration definition. Must be a valid json as a String. Required for create only.
      description:
        type: string
        description: The POD decription
        minLength: 0
        maxLength: 40
      plant:
        type: string
        description: The Plant for this POD.
        minLength: 1
        maxLength: 6
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-. ]+(?<! )$
      podId:
        type: string
        description: The POD identity.
        minLength: 1
        maxLength: 40
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-. ]+(?<! )$
      type:
        type: string
        description: The POD type.
        enum:
        - MONITOR
        - OEE
        - OPERATION
        - ORDER
        - OTHER
        - WORK_CENTER
    title: PodConfigRequest
    description: Object represents the request parameters for creating a POD given its configuration.
  PodConfigResponse:
    type: object
    required:
    - configData
    - plant
    - podId
    properties:
      configData:
        type: string
        description: The POD configuration definition. Must be a valid json as a String. Required for create only.
      createdDateTime:
        description: The POD created date and time.
        $ref: '#/definitions/Timestamp'
      description:
        type: string
        description: The POD decription
        minLength: 0
        maxLength: 40
      modifiedDateTime:
        description: The POD modified date and time.
        $ref: '#/definitions/Timestamp'
      plant:
        type: string
        description: The Plant for this POD.
        minLength: 1
        maxLength: 6
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-. ]+(?<! )$
      podId:
        type: string
        description: The POD identity.
        minLength: 1
        maxLength: 40
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-. ]+(?<! )$
      reserved:
        type: boolean
        description: Indicates if a POD is reserved or not and can not be modified or removed.
      type:
        type: string
        description: The POD type.
        enum:
        - MONITOR
        - OEE
        - OPERATION
        - ORDER
        - OTHER
        - WORK_CENTER
    title: PodConfigResponse
    description: Object represents the response to a POD creation call request.
  error:
    type: object
    properties:
      causeMessage:
        type: string
        description: Contains a technical reason for the error.
      code:
        type: string
        description: Internal error message
      correlationId:
        type: string
        description: Contains a correlation ID for the error.
      message:
        type: string
        description: Contains additional information if any.
    title: error
    description: Error response
  Timestamp:
    type: string
    format: yyyy-MM-dd'T'HH:mm:ssZ
    description: Timestamp
    title: Timestamp
