swagger: '2.0'
info:
  description: Shift is used to define the characteristics of your shift such as its beginning and end, clock-in and clock-out intervals, breaks. This API can be used to create, change, delete, and search for shifts.
  version: v1
  title: Shift
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
host: hostname
basePath: /
tags:
- name: Shift
  description: Allows you to manage shifts.
consumes:
- application/json
produces:
- application/json
paths:
  /shifts:
    get:
      tags:
      - Shift
      summary: Searches for shifts by plant and shift values.
      description: Searches for a shift for a given plant and returns the details for the same
      operationId: readUsingGET
      produces:
      - application/json
      parameters:
      - name: plant
        in: query
        description: The plant where a shift is defined.
        required: true
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      - name: shift
        in: query
        description: The shift value.
        required: false
        type: string
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      responses:
        '200':
          description: The shift was found.
          schema:
            type: array
            items:
              $ref: '#/definitions/Shift'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/ErrorResponse'
    post:
      tags:
      - Shift
      summary: Creates a shift.
      description: Creates a shift for a given plant
      operationId: createUsingPOST
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: shift
        description: The Shift to create
        required: true
        schema:
          $ref: '#/definitions/Shift'
      responses:
        '201':
          description: The shift was created.
          schema:
            $ref: '#/definitions/Shift'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '409':
          description: The shift already exists.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - Shift
      summary: Removes the given shift.
      description: Removes a shift for a given plant
      operationId: deleteUsingDELETE
      produces:
      - application/json
      parameters:
      - in: body
        name: request
        description: request
        required: true
        schema:
          $ref: '#/definitions/ShiftDeleteRequest'
      responses:
        '204':
          description: The shift was removed.
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: The shift was not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/ErrorResponse'
    patch:
      tags:
      - Shift
      summary: Updates the given shift.
      description: Updates a shift for a given plant
      operationId: updateUsingPATCH
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: shift
        description: The shift to update.
        required: true
        schema:
          $ref: '#/definitions/Shift'
      responses:
        '200':
          description: The shift was updated.
          schema:
            $ref: '#/definitions/Shift'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: The shift was not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: An internal error occured.
          schema:
            $ref: '#/definitions/ErrorResponse'
securityDefinitions:
  OAuthSecurity:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
definitions:
  Shift:
    type: object
    required:
    - plant
    - shift
    - category
    properties:
      category:
        type: string
        description: The shift category.
        enum:
        - NONE
        - RESOURCE
        - USER
        - WORKCENTER
      shift:
        type: string
        description: The shift value.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      description:
        type: string
        description: The shift description.
      plant:
        type: string
        description: The plant where a shift is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      createdOn:
        type: string
        description: The date and time when the shift was created (Plant time zone).
      modifiedOn:
        type: string
        description: The date and time when the the shift was updated (Plant time zone).
      isErp:
        type: boolean
        description: Indicates if the shift came from ERP.
      intervals:
        type: array
        description: The Shift intervals created for this shift
        items:
          $ref: '#/definitions/ShiftDefinition'
      overrides:
        type: array
        description: The Shift overrides created for this shift
        items:
          $ref: '#/definitions/ShiftOverride'
      mondayDayClass:
        description: The monday production day class.
        $ref: '#/definitions/DayClassId'
      mondayDayType:
        type: string
        description: Indicates if monday is a production day or not
        enum:
        - NONPRODUCTION
        - PRODUCTION
      tuesdayDayClass:
        description: The tuesday production day class.
        $ref: '#/definitions/DayClassId'
      tuesdayDayType:
        type: string
        description: Indicates if tuesday is a production day or not
        enum:
        - NONPRODUCTION
        - PRODUCTION
      wednesdayDayClass:
        description: The wednesday production day class.
        $ref: '#/definitions/DayClassId'
      wednesdayDayType:
        type: string
        description: Indicates if wednesday is a production day or not
        enum:
        - NONPRODUCTION
        - PRODUCTION
      thursdayDayClass:
        description: The thursday production day class.
        $ref: '#/definitions/DayClassId'
      thursdayDayType:
        type: string
        description: Indicates if thursday is a production day or not
        enum:
        - NONPRODUCTION
        - PRODUCTION
      fridayDayClass:
        description: The friday production day class.
        $ref: '#/definitions/DayClassId'
      fridayDayType:
        type: string
        description: Indicates if friday is a production day or not
        enum:
        - NONPRODUCTION
        - PRODUCTION
      saturdayDayClass:
        description: The saturday production day class.
        $ref: '#/definitions/DayClassId'
      saturdayDayType:
        type: string
        description: Indicates if saturday is a production day or not
        enum:
        - NONPRODUCTION
        - PRODUCTION
      sundayDayClass:
        description: The sunday production day class.
        $ref: '#/definitions/DayClassId'
      sundayDayType:
        type: string
        description: Indicates if sundayDay is a production day or not
        enum:
        - NONPRODUCTION
        - PRODUCTION
      customValues:
        type: array
        description: The shift custom values.
        items:
          $ref: '#/definitions/CustomValue'
    title: Shift
    description: The shift.
  ShiftDefinition:
    type: object
    required:
    - validFrom
    - beginTime
    - endTime
    - laborAssignment
    properties:
      beginTime:
        type: string
        description: The time when shift begins.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      clockInStart:
        type: string
        description: The earliest time users can clock in.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      clockInEnd:
        type: string
        description: The latest time users can clock in.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      clockOutStart:
        type: string
        description: The earliest time users can clock out.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      clockOutEnd:
        type: string
        description: The latest time users can clock out.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      endTime:
        type: string
        description: The time when shift ends.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      laborAssignment:
        type: string
        description: Specifies the day the system logs the shift time to when the shift spans midnight.
        enum:
        - ACTUAL_DAY
        - SHIFT_START_DAY
        - SHIFT_END_DAY
      shiftDefinitionBreaks:
        type: array
        description: Specifies shift breaks.
        items:
          $ref: '#/definitions/ShiftDefinitionBreak'
      validFrom:
        type: string
        description: Shift valid date from.
      validTo:
        type: string
        description: Shift valid date to.
      mondayOverride:
        description: Specifies specific shift definition for Monday.
        $ref: '#/definitions/ShiftDefinitionOverride'
      tuesdayOverride:
        description: Specifies specific shift definition for Tuesday.
        $ref: '#/definitions/ShiftDefinitionOverride'
      wednesdayOverride:
        description: Specifies specific shift definition for Wednesday.
        $ref: '#/definitions/ShiftDefinitionOverride'
      thursdayOverride:
        description: Specifies specific shift definition for Thursday.
        $ref: '#/definitions/ShiftDefinitionOverride'
      fridayOverride:
        description: Specifies specific shift definition for Friday.
        $ref: '#/definitions/ShiftDefinitionOverride'
      saturdayOverride:
        description: Specifies specific shift definition for Saturday.
        $ref: '#/definitions/ShiftDefinitionOverride'
      sundayOverride:
        description: Specifies specific shift definition for Sunday.
        $ref: '#/definitions/ShiftDefinitionOverride'
    title: ShiftDefinition
    description: The shift definition.
  ShiftDefinitionBreak:
    type: object
    required:
    - beginTime
    - endTime
    - breakType
    properties:
      beginTime:
        type: string
        description: The start time when the break begins.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      breakType:
        description: The shift break type value.
        $ref: '#/definitions/BreakTypeId'
      endTime:
        type: string
        description: The start time when the break ends.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
    title: ShiftDefinitionBreak
    description: The shift definition break.
  ShiftDefinitionOverride:
    type: object
    required:
    - beginTime
    - endTime
    - laborAssignment
    properties:
      beginTime:
        type: string
        description: The time when shift begins.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      clockInEnd:
        type: string
        description: The latest time users can clock in.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      clockInStart:
        type: string
        description: The earliest time users can clock in.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      clockOutEnd:
        type: string
        description: The latest time users can clock out.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      clockOutStart:
        type: string
        description: The earliest time users can clock out.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      endTime:
        type: string
        description: The time when shift ends.
        pattern: ^(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$|^(?:2[0-3]|[01][0-9]):[0-5][0-9]$
      laborAssignment:
        type: string
        description: Specifies the day the system logs the shift time to when the shift spans midnight.
        enum:
        - ACTUAL_DAY
        - SHIFT_END_DAY
        - SHIFT_START_DAY
      shiftDefinitionBreaks:
        type: array
        description: Specifies shift breaks.
        items:
          $ref: '#/definitions/ShiftDefinitionBreak'
    title: ShiftDefinitionOverride
    description: The shift override definition.
  ShiftDeleteRequest:
    type: object
    required:
    - plant
    - shift
    properties:
      plant:
        type: string
        description: The plant where a shift is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      shift:
        type: string
        description: The shift value.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
    title: ShiftDeleteRequest
    description: Shift delete request.
  ShiftOverride:
    type: object
    required:
    - date
    - dayClass
    - dayType
    properties:
      date:
        type: string
        description: The shift override date.
      dayClass:
        description: The day class.
        $ref: '#/definitions/DayClassId'
      dayType:
        type: string
        description: The day type.
        enum:
        - NONPRODUCTION
        - PRODUCTION
    title: ShiftOverride
    description: The shift override.
  BreakTypeId:
    type: object
    required:
    - breakType
    - plant
    properties:
      breakType:
        type: string
        description: The break type value.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      plant:
        type: string
        description: The plant where a break type is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
    title: BreakTypeId
    description: The shift break type unique data.
  DayClassId:
    type: object
    required:
    - dayClass
    - plant
    properties:
      dayClass:
        type: string
        description: The day class value.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
      plant:
        type: string
        description: The plant where a day class is defined.
        pattern: ^(?! )[0-9A-Z_$!)(+~@^=\-*. ]+(?<! )$
    title: DayClassId
    description: The Day Class unique data.
  CustomValue:
    type: object
    properties:
      attribute:
        type: string
      value:
        type: string
    title: CustomValue
  ErrorResponse:
    type: object
    properties:
      causeMessage:
        type: string
      code:
        type: string
      correlationId:
        type: string
      message:
        type: string
    title: ErrorResponse
externalDocs:
  description: Prepare for API Integration
  url: https://help.sap.com/docs/sap-digital-manufacturing/operations-guide/prepare-for-api-integration
schemes:
- https
security:
- OAuthSecurity: []
x-sap-shortText: Maintain shifts for a given plant
x-servers:
- url: https://api.{regionHost}/shift/v1
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication server where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us10.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
