swagger: '2.0'
info:
  title: Manage Identifiers Configuration
  description: 'You can use this service to manage identifier configuration for specific events at a plant. You can define numbering patterns for event types such as SFC Release or SFC Serialize. '
  version: v1
  contact:
    name: SAP Digital Manufacturing Operations
    email: sap-dmoperation@sap.com
externalDocs:
  description: SAP Digital Manufacturing Help Portal
  url: https://help.sap.com/docs/sap-digital-manufacturing
host: hostname
basePath: /
x-sap-shortText: Create and maintain Identifiers configuration
x-servers:
- url: https://api.{regionHost}/numbering/v1/identifier
  description: Base URL
  templates:
    regionHost:
      description: The data center where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.dmc.cloud.sap
      - us10.dmc.cloud.sap
      - eu20.dmc.cloud.sap
      - us20.dmc.cloud.sap
      - test.eu10.dmc.cloud.sap
      - test.us10.dmc.cloud.sap
      - test.eu20.dmc.cloud.sap
      - test.us20.dmc.cloud.sap
      default: test.eu10.dmc.cloud.sap
    tokenHost:
      description: The authentication token server where SAP Digital Manufacturing is provisioned for your organization
      enum:
      - eu10.hana.ondemand.com
      - us10.hana.ondemand.com
      - eu20.hana.ondemand.com
      - us20.hana.ondemand.com
      default: eu10.hana.ondemand.com
schemes:
- https
securityDefinitions:
  OauthClientCredentials:
    type: oauth2
    tokenUrl: https://{subdomain}.authentication.{tokenHost}/oauth/token
    flow: application
security:
- OauthClientCredentials: []
produces:
- application/json
consumes:
- application/json
tags:
- name: Manage Identifiers Configuration
paths:
  /config:
    post:
      tags:
      - Manage Identifiers Configuration
      summary: Create identifiers configuration.
      description: With this operation, identifiers configuration for business objects upon specified events at a plant can be created.
      consumes:
      - application/json
      parameters:
      - in: body
        name: request
        description: Request object to create an identifier configuration.
        required: true
        schema:
          $ref: '#/definitions/CreateIdentifierConfigurationRequest'
      responses:
        '200':
          description: Identifier configuration has been created successfully.
          schema:
            $ref: '#/definitions/IdentifierConfigurationResponse'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      tags:
      - Manage Identifiers Configuration
      summary: Update identifiers configuration.
      description: With this operation, identifiers configuration for business objects upon specified events at a plant can be updated.
      consumes:
      - application/json
      parameters:
      - in: body
        name: request
        description: Request object to update an identifier configuration.
        required: true
        schema:
          $ref: '#/definitions/UpdateIdentifierConfigurationRequest'
      responses:
        '200':
          description: ' Identifier configuration has been updated successfully.'
          schema:
            $ref: '#/definitions/IdentifierConfigurationResponse'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/ErrorResponse'
    get:
      tags:
      - Manage Identifiers Configuration
      summary: Read identifiers configuration.
      description: With this operation, identifiers configuration for business objects upon specified events at a plant can be retrieved.
      consumes:
      - application/json
      parameters:
      - in: query
        name: plant
        description: Plant to read an identifier configuration.
        required: true
        type: string
      - in: query
        name: id
        description: Request ID to retrieve an identifier configuration.
        required: true
        type: string
      responses:
        '200':
          description: ' Read an identifier configuration successfully.'
          schema:
            $ref: '#/definitions/IdentifierConfigurationResponse'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - Manage Identifiers Configuration
      summary: Delete identifiers configuration.
      description: With this operation, identifiers configuration for business objects upon specified events at a plant can be deleted.
      consumes:
      - application/json
      parameters:
      - in: query
        name: plant
        description: Plant to delete an identifier configuration.
        required: true
        type: string
      - in: query
        name: id
        description: Request ID to delete an identifier configuration.
        required: true
        type: string
      responses:
        '200':
          description: ' Deleted an identifier configuration successfully.'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/ErrorResponse'
  /materialIdentifierConfigurations:
    get:
      tags:
      - Read All Identifiers Configuration
      summary: Read all identifiers configurations.
      description: With this operation, you can retrieve all identifiers configurations for the specified event at a plant. You can define the event types like SFC Release, SFC Serialize etc.
      consumes:
      - application/json
      parameters:
      - in: query
        name: plant
        description: Plant to read identifier configurations.
        required: true
        type: string
      - in: query
        name: event
        description: 'Read Identifier Configurations based on event types like SFC Release, SFC Serialize etc. '
        required: true
        type: string
      responses:
        '200':
          description: ' Read identifier configuration successfully.'
          schema:
            $ref: '#/definitions/EventBasedIdentifierConfigurationResponse'
        '400':
          description: The HTTP request is bad or invalid and cannot be processed by the server.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: You are not authorized to call this resource.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Accessing the resource you are trying to reach is forbidden.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: One of the related elements is not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: There was an internal error somewhere in the call chain.
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  CreateIdentifierConfigurationRequest:
    type: object
    description: Request object to manage identifiers.
    required:
    - plant
    - nextNumberType
    - currentSequence
    - sourceSystem
    - sequenceBase
    properties:
      plant:
        description: Plant where create identifier configuration has to be performed.
        type: string
      material:
        type: object
        description: The material that you want to associate with the numbering pattern.
        $ref: '#/definitions/Material'
      materialGroup:
        description: The material group that you want to associate with the numbering pattern.
        type: string
      nextNumberType:
        description: To define a numbering pattern types like SFC Release, SFC Serialize etc.
        type: string
      prefix:
        description: The prefix of the numbering pattern.
        type: string
      suffix:
        description: The suffix of the numbering pattern.
        type: string
      sequenceBase:
        description: The number base of the sequence portion of the numbering pattern.
        type: number
      sequenceLength:
        description: The number of characters for the sequence portion of the numbering pattern.
        type: number
      maxSequence:
        description: The upper limit for the sequence portion of the numbering pattern.
        type: string
      minSequence:
        description: The lower limit for the sequence portion of the numbering pattern.
        type: string
      increment:
        description: The value by which you want to increment the current sequence number after a new number is generated.
        type: string
      currentSequence:
        description: The next number of the sequence portion of the numbering pattern.
        type: string
      sourceSystem:
        description: Source System.
        type: string
      extension:
        description: Extension is used to generate identifiers for the different numbering events.
        type: string
  Material:
    type: object
    description: Request object for material.
    properties:
      material:
        description: The material that you want to associate with the numbering pattern.
        type: string
      version:
        description: The version of the material that you want to associate with the numbering pattern.
        type: string
  IdentifierConfigurationResponse:
    type: object
    description: The Create Identifiers response.
    properties:
      plant:
        description: Plant where create identifier has to be performed.
        type: string
      id:
        description: A unique ID is associated for each identifier configuration.
        type: string
      version:
        description: The version of the material that you want to associate with the numbering pattern.
        type: number
      materialContext:
        description: The material that you want to associate with the numbering pattern.
        type: string
      materialGroup:
        description: The material group that you want to associate with the numbering pattern.
        type: string
      propertyMatchers:
        type: array
        description: Property matchers for which create identifier has been performed.
        items:
          $ref: '#/definitions/PropertyMatchers'
      nextNumberType:
        description: To define a numbering pattern types like SFC Release, SFC Serialize etc.
        type: string
      prefix:
        description: The prefix of the numbering pattern.
        type: string
      suffix:
        description: The suffix of the numbering pattern.
        type: string
      sequenceBase:
        description: The number base of the sequence portion of the numbering pattern.
        type: number
      sequenceLength:
        description: The number of characters for the sequence portion of the numbering pattern.
        type: number
      maxSequence:
        description: The upper limit for the sequence portion of the numbering pattern.
        type: string
      minSequence:
        description: The lower limit for the sequence portion of the numbering pattern.
        type: string
      increment:
        description: The value by which you want to increment the current sequence number after a new number is generated.
        type: string
      currentSequence:
        description: The next number of the sequence portion of the numbering pattern.
        type: string
      sourceSystem:
        description: Source System.
        type: string
      extension:
        description: Extension is used to generate identifiers for the different numbering events.
        type: string
      sample:
        description: Displays a sample of the next number pattern based on the entered and saved values.
        type: string
  UpdateIdentifierConfigurationRequest:
    type: object
    description: Request object to manage identifiers.
    required:
    - plant
    - id
    - sequenceBase
    - currentSequence
    - sourceSystem
    properties:
      plant:
        description: Plant where update identifier configuration has to be performed.
        type: string
      id:
        description: A unique ID is associated for each identifier configuration.
        type: string
      prefix:
        description: The prefix of the numbering pattern.
        type: string
      suffix:
        description: The suffix of the numbering pattern.
        type: string
      sequenceBase:
        description: The number base of the sequence portion of the numbering pattern.
        type: number
      sequenceLength:
        description: The number of characters for the sequence portion of the numbering pattern.
        type: number
      maxSequence:
        description: The upper limit for the sequence portion of the numbering pattern.
        type: string
      minSequence:
        description: The lower limit for the sequence portion of the numbering pattern.
        type: string
      increment:
        description: The value by which you want to increment the current sequence number after a new number is generated.
        type: string
      currentSequence:
        description: The next number of the sequence portion of the numbering pattern.
        type: string
      sourceSystem:
        description: Source System.
        type: string
      extension:
        description: Extension is used to generate identifiers for the different numbering events.
        type: string
  PropertyMatchers:
    type: object
    description: Response object for property matchers.
    properties:
      name:
        description: Name
        type: string
      value:
        description: Value
        type: string
      priority:
        description: Priority
        type: number
  EventBasedIdentifierConfigurationResponse:
    type: object
    description: Identifier Configuration response
    properties:
      odata.context:
        description: Odata Identifier Configuration entity
        type: string
      value:
        type: array
        description: Event based Identifier configurations.
        items:
          $ref: '#/definitions/MaterialIdentfierConfiguration'
  MaterialIdentfierConfiguration:
    type: object
    description: Identifier Configuration
    properties:
      id:
        description: A unique ID is associated for each identifier configuration.
        type: string
      plant:
        description: Plant where create identifier has to be performed.
        type: string
      eventName:
        description: Event types like SFC Release, SFC Serialize etc
        type: string
      targetBusinessObject:
        description: targetBusinessObject
        type: string
      sourceSystem:
        description: sourceSystem
        type: string
      extension:
        description: Extension is used to generate identifiers for the different numbering events.
        type: string
      version:
        description: The version of the material that you want to associate with the numbering pattern.
        type: number
      pattern:
        description: Pattern for which create identifier has been performed.
        $ref: '#/definitions/Pattern'
      sequence:
        type: object
        description: Sequence number configuration.
        $ref: '#/definitions/Sequence'
      identPropMatcher:
        type: array
        description: Property matchers for which create identifier has been performed.
        items:
          $ref: '#/definitions/PropertyMatchers'
  Sequence:
    type: object
    description: Response object for sequence.
    properties:
      base:
        description: The number base of the sequence portion of the numbering pattern.
        type: number
      length:
        description: The number of characters for the sequence portion of the numbering pattern.
        type: number
      minimumValue:
        description: The lower limit for the sequence portion of the numbering pattern.
        type: number
      maximumValue:
        description: The upper limit for the sequence portion of the numbering pattern.
        type: number
      currentValue:
        description: The next number of the sequence portion of the numbering pattern.
        type: number
      increment:
        description: The value by which you want to increment the current sequence number after a new number is generated.
        type: number
  Pattern:
    type: object
    description: Response object for pattern.
    properties:
      prefix:
        description: The prefix of the numbering pattern.
        type: string
      suffix:
        description: The suffix of the numbering pattern.
        type: string
  ErrorResponse:
    type: object
    properties:
      causeMessage:
        type: string
        description: Contains technical reason for the error.
      code:
        type: string
        description: Internal error message
      correlationId:
        type: string
        description: Contains correlationId for the error.
      message:
        type: string
        description: Contains additional information, if any
    title: ErrorResponse
    description: Error response.
