/*
    Creates table Users.
*/
CREATE TABLE Z_SFC_ASSY
(
    id serial PRIMARY KEY,
    SFC_BO NCHAR(412),
    SHOP_ORDER_BO NCHAR(412),
    RESOURCE_BO NCHAR(412),
    OPERATION_BO NCHAR(412),
    COMPONENT_BO NCHAR(412),
    QTY DECIMAL(13,2),
    BOM_COMPONENT_BO NCHAR(412),
    INSUSER NCHAR(40),
    INSDATE TIMESTAMP,
    UPDUSER NCHAR(40),
    UPDDATE TIMESTAMP,
    IS_DELETED NCHAR(1)
);
create unique index idx_t_id_a on Z_SFC_ASSY  (SFC_BO,OPERATION_BO,BOM_COMPONENT_BO);
